language: python

python:
  - 2.7

dist: trusty

notifications:
  email: false

before_install:
  # Temporal fix for networking problem: https://github.com/travis-ci/travis-ci/issues/1484
  - echo "127.0.1.1 "`hostname` | sudo tee /etc/hosts

  # export path
  - export PATH=$HOME/miniconda2/bin/:$PATH
  - bash tests/setup-tests.sh

install:
  - pip install coveralls
  - pip install -r requirements.txt
  - pip install .

script:
  - py.test --capture=no --cov autoseq --ignore=tests/integration tests/

after_success:
    - coveralls
